### ISSUE TITLE
Add within-VCF file partitioning

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/bio2zarr#12]
It would be useful to partition input VCF files so that we can explode them in parallel. This can directly reuse the code in sgkit, which uses the indexes to partition files.

Note, we need to be careful about indels that span partitions. This is done by filtering variants that don't start in the region, as sgkit does [here](https://github.com/pystatgen/sgkit/blob/d32b8714e026b5e0ab49812a87174edbd829b26a/sgkit/io/vcf/vcf_reader.py#L109)

@tomwhite I think it would be simplest if we just copied the relevant code from sgkit over here. I can do this, but it it would be nice if you got the due git-cred for it. Would you be interested in opening a PR that copies in the relevant code and tests with minimal modifications, and then I can factor in to the current structure?

Doesn't matter what files they go in - could just make a "ported_vcf.py" module with new code, and then copy tests directly into ``tests`` directory or something?

**Comment by jeromekelleher** [comment]
We basically want the https://github.com/pystatgen/sgkit/blob/main/sgkit/io/vcf/vcf_partition.py file plus indexes stuff, I think

**Comment by tomwhite** [comment]
> Would you be interested in opening a PR that copies in the relevant code and tests with minimal modifications, and then I can factor in to the current structure?

Sure, I can do that.
